/**
 * API Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LabelDto { 
    _id: string;
    userId: string;
    labelId: string;
    name: string;
    type: LabelDto.TypeEnum;
    messageListVisibility: LabelDto.MessageListVisibilityEnum;
    labelListVisibility: LabelDto.LabelListVisibilityEnum;
}
export namespace LabelDto {
    export type TypeEnum = 'system' | 'user';
    export const TypeEnum = {
        System: 'system' as TypeEnum,
        User: 'user' as TypeEnum
    };
    export type MessageListVisibilityEnum = 'show' | 'hide';
    export const MessageListVisibilityEnum = {
        Show: 'show' as MessageListVisibilityEnum,
        Hide: 'hide' as MessageListVisibilityEnum
    };
    export type LabelListVisibilityEnum = 'labelShow' | 'labelShowIfUnread' | 'labelHide';
    export const LabelListVisibilityEnum = {
        LabelShow: 'labelShow' as LabelListVisibilityEnum,
        LabelShowIfUnread: 'labelShowIfUnread' as LabelListVisibilityEnum,
        LabelHide: 'labelHide' as LabelListVisibilityEnum
    };
}


