export * from './app.service';
import { AppService } from './app.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './gmail.service';
import { GmailService } from './gmail.service';
export * from './health.service';
import { HealthService } from './health.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AppService, AuthService, DashboardService, GmailService, HealthService, UsersService];
